#!/bin/bash
# Lab Scanner - Setup Summary & Next Steps

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                   LAB SCANNER - SETUP COMPLETE               ║"
echo "║              Professional Vulnerability Scanner              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

echo "📍 PROJECT LOCATION: ~/Desktop/scanner2/"
echo ""

echo "📦 INSTALLATION PACKAGE CONTENTS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1️⃣  INSTALLER.sh"
echo "      → Main installation script (run this first!)"
echo "      → Creates virtual environment, installs dependencies"
echo "      → Sets up desktop shortcuts and CLI commands"
echo "      → Takes 2-3 minutes"
echo ""
echo "  2️⃣  LAUNCHER.sh"
echo "      → Starts both API and Dashboard services"
echo "      → Opens dashboard in browser automatically"
echo "      → Logs to /tmp/lab-scanner-*.log"
echo ""
echo "  3️⃣  Lab-Scanner.desktop"
echo "      → Desktop shortcut (auto-created on desktop)"
echo "      → Double-click to launch Lab Scanner"
echo "      → Alternative to terminal command"
echo ""
echo "  4️⃣  verify.sh"
echo "      → Pre-installation verification script"
echo "      → Checks Python, pip, ports, requirements"
echo "      → Run before installing if unsure"
echo ""
echo "  5️⃣  README.md"
echo "      → Complete project documentation"
echo "      → Features, architecture, troubleshooting"
echo ""
echo "  6️⃣  QUICKSTART.md"
echo "      → Quick reference guide"
echo "      → Installation, launching, basic usage"
echo ""

echo ""
echo "🚀 INSTALLATION STEPS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Step 1: Verify Requirements (optional)"
echo "  ────────────────────────────────────────"
echo "  bash ~/Desktop/scanner2/verify.sh"
echo ""
echo "  This checks:"
echo "    ✓ Python 3.8+ installed"
echo "    ✓ pip3 available"
echo "    ✓ Ports 5000 and 8000 are free"
echo "    ✓ Installation files present"
echo ""

echo "  Step 2: Run Installer"
echo "  ────────────────────────────────────────"
echo "  bash ~/Desktop/scanner2/INSTALLER.sh"
echo ""
echo "  The installer will:"
echo "    1. Check system requirements"
echo "    2. Create ~/.local/share/lab-scanner/"
echo "    3. Create Python virtual environment"
echo "    4. Install all dependencies (pip packages)"
echo "    5. Initialize database"
echo "    6. Create desktop shortcut"
echo "    7. Create CLI command: lab-scanner"
echo ""
echo "  ⏱️  Takes 2-3 minutes (mostly downloading packages)"
echo ""

echo "  Step 3: Launch Lab Scanner"
echo "  ────────────────────────────────────────"
echo "  Choose one method:"
echo ""
echo "  Method A: Desktop Icon (Easiest)"
echo "    → Look for 'Lab Scanner' on your desktop"
echo "    → Double-click it"
echo "    → Dashboard opens automatically in browser"
echo ""
echo "  Method B: Terminal Command"
echo "    → Open any terminal"
echo "    → Type: lab-scanner"
echo "    → (Requires terminal restart after installation)"
echo ""
echo "  Method C: Direct Script"
echo "    → bash ~/.local/share/lab-scanner/launcher.sh"
echo ""

echo ""
echo "📊 AFTER INSTALLATION:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Dashboard Access:"
echo "    🌐 URL: http://localhost:5000"
echo "    🔌 API: http://localhost:8000/api"
echo "    📖 API Docs: http://localhost:8000/api/docs"
echo ""
echo "  Network Discovery:"
echo "    1. Enter CIDR range (e.g., 192.168.1.0/24)"
echo "    2. Click 'DISCOVER ACTIVE HOSTS'"
echo "    3. Click discovered IPs to scan them"
echo ""
echo "  Full Vulnerability Scan:"
echo "    1. Enter target IP address manually OR click discovered host"
echo "    2. Select 'Full Scan' (recommended)"
echo "    3. Click 'START FULL SCAN'"
echo "    4. View results with open ports, services, vulnerabilities"
echo ""

echo ""
echo "🐛 TROUBLESHOOTING:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  If something goes wrong:"
echo ""
echo "  1. Check logs:"
echo "     tail -20 /tmp/lab-scanner-api.log"
echo "     tail -20 /tmp/lab-scanner-dashboard.log"
echo ""
echo "  2. Verify Python installation:"
echo "     python3 --version"
echo ""
echo "  3. Check if ports are free:"
echo "     ss -tuln | grep -E '5000|8000'"
echo ""
echo "  4. Reinstall from scratch:"
echo "     rm -rf ~/.local/share/lab-scanner"
echo "     bash ~/Desktop/scanner2/INSTALLER.sh"
echo ""
echo "  5. Run verification script:"
echo "     bash ~/Desktop/scanner2/verify.sh"
echo ""

echo ""
echo "📚 DOCUMENTATION:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  📖 README.md"
echo "     Full documentation, architecture, technology stack"
echo ""
echo "  🚀 QUICKSTART.md"
echo "     Quick reference, usage guide, advanced topics"
echo ""
echo "  💻 API Documentation"
echo "     http://localhost:8000/api/docs (interactive)"
echo ""

echo ""
echo "✨ FEATURES:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ✓ Network Discovery (CIDR ranges)"
echo "  ✓ Multi-threaded Port Scanning (100+ threads)"
echo "  ✓ Service Detection & Banner Grabbing"
echo "  ✓ Web Vulnerability Scanning"
echo "  ✓ CVSS-style Risk Scoring"
echo "  ✓ Matrix-Themed Dark Dashboard"
echo "  ✓ RESTful API with Swagger Docs"
echo "  ✓ Plugin System for Custom Scanners"
echo "  ✓ Distributed Agent Architecture"
echo ""

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "👉 READY TO BEGIN? Run the installer:"
echo ""
echo "   bash ~/Desktop/scanner2/INSTALLER.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 Lab Scanner v1.0 - Professional Vulnerability Scanner"
echo "📍 Inspired by: nmap, Nikto, Metasploit"
echo ""
